[project]
name = "heckbot"
description = "For-fun Discord bot"
version = "0.1.0"
authors = [
    { name = "Julian Espada", email = "jesp1999@gmail.com" }
]

dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}